server/print3dstore/blueprints/forms/order.py
from wtforms import Form, FileField, FormField, HiddenField, IntegerField, Label, SelectField, StringField, TelField, validators
from wtforms.widgets import FileInput
from print3dstore.models import Material

from print3dstore.blueprints.forms.base import CsrfBaseForm

class OrderForm(CsrfBaseForm):
    order_heading = HiddenField(label="Order details")
    stl_models = FileField(
        label="Models",
        validators=[validators.input_required()],
        widget=FileInput(False),
        render_kw={"accept": ".stl", "class": "form-control"}
    )
    material = SelectField(
        label="Material",
        choices=[
            ("pla", "PLA"),
            ("petg", "PETG"),
            ("tpu", "TPU"),
        ],
        render_kw={"class": "form-select"}
    )
    color = SelectField(
        label="Color",
        choices=[
            ("red", "Red"),
            ("blue", "Blue"),
            ("green", "Green"),
        ],
        render_kw={"class": "form-select"}
    )
    delivery_heading = HiddenField(label="Delivery address details")
    city = StringField(
        label="City",
        validators=[validators.input_required()],
        render_kw={"class": "form-control"}
    )
    postal_code = StringField(
        label="Postal Code",
        validators=[validators.input_required()],
        render_kw={"class": "form-control"}
    )
    address_line1 = StringField(
        label="Address line 1",
        validators=[validators.input_required()],
        render_kw={"class": "form-control"}
    )
    address_line2 = StringField(
        label="Address line 2",
        validators=[validators.optional()],
        render_kw={"class": "form-control"}
    )
    phone = TelField(
        label="Phone number",
        render_kw={"class": "form-control"}
    )
    payment_heading = HiddenField(label="Payment")
    payment_method = SelectField(
        label="Payment method",
        validators=[validators.input_required()],
        choices=["Credit card", "Cash"],
        render_kw={"class": "form-select"}
    )

class OrderEditForm(OrderForm):
    status = SelectField("Status", choices=['', ''])
    stl_models = None

server/print3dstore/blueprints/auth.py
import functools
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for, make_response
from werkzeug.security import check_password_hash, generate_password_hash
from psycopg2.errors import UniqueViolation
from print3dstore.errors import RequestException
from print3dstore.models import Role, User, UserRole, db
from print3dstore.wrapper_functions import error_handler
from .forms.auth import AuthForm, RegisterForm

bp = Blueprint("auth", __name__, url_prefix="/auth")

@bp.route("/register", methods=["GET", "POST"])
@error_handler
def register():
    form = RegisterForm()
    if request.method == "POST":
        form.process(request.form)
        if not form.validate():
            raise RequestException(form.errors, 400)
        email = request.form["email"]
        password = request.form["password"]
        errors = []

        if email == "":
            errors.append("Email is required.")
        if password == "":
            errors.append("Password is required.")

        user_email = db.session.execute(
            db.select(User).where(User.email == email)
        ).all()

        if len(user_email) > 0:
            flash("User with that email already exists", "danger")
            return redirect(url_for("auth.register"))

        if len(errors) == 0:
            role = db.session.scalar(
                db.select(Role).filter_by(name="user")
            )
            new_user = User(
                email=email,
                password=generate_password_hash(password),
                first_name=request.form["first_name"],
                last_name=request.form["last_name"],
                city=request.form["city"],
                postal_code=request.form["postal_code"],
                address_line1=request.form["address_line1"],
                address_line2=request.form["address_line2"],
                phone=request.form["phone"],
            )
            user_role = UserRole()
            user_role.user = new_user
            user_role.role = role
            db.session.add(new_user)
            db.session.add(user_role)
            db.session.commit()
            
            flash("User successfully registered.", "success")

            return redirect(url_for("auth.login"))
        else:
            raise RequestException(" ".join(errors), 400)

    return render_template("auth/user_form.html", form=form, action="register")


@bp.route("/login", methods=("GET", "POST"))
@error_handler
def login():
    form = AuthForm(request.form)
    if request.method == "POST" and form.validate():
        user = User.query.filter_by(email=request.form["email"]).first()
        if user is None:
            raise RequestException("User with that email is not found", 400)
        if not check_password_hash(user.password, request.form["password"]):
            raise RequestException("Incorrect password", 400)

        session["user_id"] = user.id

        redirect_to_url = url_for("main.root")
        if session.get("redirected_from_url") is not None:
            redirect_to_url = session["redirected_from_url"]

        flash("Successfully logged in", "success")

        return redirect(redirect_to_url)

    return render_template("auth/user_form.html", form=form, action="login")


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")
    if user_id is None:
        g.user = None
        g.roles = None
    else:
        g.user = db.session.get(User, user_id)
        if g.user is None:
            session.clear()
            g.roles = None
        else:
            g.roles = g.user.roles


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            session["redirected_from_url"] = request.url
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view


@bp.route("/logout")
@error_handler
def logout():
    session.clear()
    g.user = None
    g.role = None

    flash("Successfully logged out!", "success")

    return redirect(url_for("main.root"))

server/print3dstore/blueprints/order.py
from flask import Blueprint, current_app, flash, g, make_response, redirect, render_template, request, url_for

import uuid

from print3dstore.wrapper_functions import error_handler
from print3dstore.errors import RequestException
from print3dstore.blueprints.auth import login_required
from print3dstore.models import PaymentGateway, Spool, User, db, File, Material, Order, StlModel

from .forms.order import OrderForm

from .tasks import tasks

bp = Blueprint("order", __name__)

@bp.route("/order", methods=["GET", "POST"])
@error_handler
@login_required
def order():
    materials = db.session.scalars(db.select(Material)).all()
    spools = db.session.scalars(db.select(Spool)).all()
    payment_gateways = db.session.scalars(db.select(PaymentGateway)).all()
    form = OrderForm()
    form.material.choices = list(
        map(
            lambda material: material.name,
            materials
        )
    )
    form.color.choices = list(
        map(
            lambda spool: spool.color,
            spools
        )
    )
    form.payment_method.choices = list(
        map(
            lambda payment_gateway: payment_gateway.name,
            payment_gateways
        )
    )
    if g.user is not None:
        form.city.data = g.user.city
        form.postal_code.data = g.user.postal_code
        form.address_line1.data = g.user.address_line1
        form.address_line2.data = g.user.address_line2
        form.phone.data = g.user.phone

    if request.method == "POST":
        form.process(request.form)
        form.stl_models.raw_data = request.files.getlist("stl_models")
        if not form.validate():
            return render_template("order.html", form=form)

        stl_files = request.files.getlist("stl_models")
        material_name = request.form.get("material")
        color = request.form.get("color")
        city = request.form.get("city")
        postal_code = request.form.get("postal_code")
        address_line1 = request.form.get("address_line1")
        address_line2 = request.form.get("address_line2")
        phone = request.form.get("phone")
        payment_method = request.form.get("payment_method")

        material = db.first_or_404(
            db.select(Material).filter_by(name=material_name),
            description=f"No such material found in our database"
        )

        user = db.get_or_404(
            User, g.user.id
        )

        user.address_line1 = address_line1
        user.address_line2 = address_line2
        user.city = city
        user.postal_code = postal_code
        user.phone = phone

        payment_gateway = db.first_or_404(
            db.select(PaymentGateway).filter_by(name=payment_method)
        )

        files_added = []
        for stl_file in stl_files:
            mat = material_name.upper().replace(" ", "_")
            col = color.upper().replace(" ", "_")
            file_name = stl_file.filename.replace(" ", "_")

            file_path = f"{current_app.root_path}/media/{mat}-{col}-{str(uuid.uuid4())}-{file_name}"
            stl_file.save(file_path)
            new_file = File(full_path=file_path)

            db.session.add(new_file)
            files_added.append(new_file)

        stl_models = []
        for file in files_added:
            stl_model = StlModel(file=file, color=color)
            stl_model.material = material

            db.session.add(stl_model)
            stl_models.append(stl_model)

        order = Order(
            user=g.user,
            stl_models=stl_models,
            payment_gateway=payment_gateway,
            address_line1 = address_line1,
            address_line2 = address_line2,
            city = city,
            postal_code = postal_code,
            phone = phone,
        )

        db.session.add(order)

        db.session.commit()

        # create the tasks after committing to the database
        for stl_model in stl_models:
            tasks.slice.delay(stl_model.file.full_path, material.id)

        flash("Order has been saved", "success")

        return redirect(url_for("main.root"))
    
    return render_template("order.html", form=form)


@bp.route('/slice/retry/<order_id>', methods=('GET',))
@error_handler
@login_required
def retry_slice(order_id: int):
    order = db.get_or_404(Order, order_id)
    for stl_model in order.stl_models:
        tasks.slice.delay(stl_model.file.full_path, stl_model.material_id)
    
    return redirect(url_for('profile.orders'))

server/print3dstore/blueprints/profile.py
from flask import Blueprint, current_app, g, make_response, redirect, render_template, request, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from print3dstore.errors import RequestException
from print3dstore.wrapper_functions import error_handler
from print3dstore.blueprints.auth import login_required
from print3dstore.blueprints.forms.auth import ChangePasswordForm, ProfileForm
from print3dstore.models import User, db

bp = Blueprint("profile", __name__, url_prefix="/profile")

@bp.route("")
@error_handler
def info():
    if g.user is None:
        raise RequestException("Unauthorized", 401)
    return render_template("profile/profile.html")

@bp.route("/orders")
@error_handler
@login_required
def orders():
    if g.user is None:
        raise RequestException("Unauthorized", 401)
    
    return render_template("profile/orders.html")

@bp.route("/settings", methods=["GET", "POST"])
@error_handler
@login_required
def settings():
    if g.user is None:
        raise RequestException("Unauthorized", 401)

    address_form = ProfileForm()
    password_form = ChangePasswordForm()
    
    address_form.first_name.data = g.user.first_name
    address_form.last_name.data = g.user.last_name
    address_form.address_line1.data = g.user.address_line1
    address_form.address_line2.data = g.user.address_line2
    address_form.city.data = g.user.city
    address_form.postal_code.data = g.user.postal_code
    address_form.phone.data = g.user.phone

    if request.method == "POST":
        user = db.get_or_404(User, g.user.id)

        user.first_name = request.form["first_name"]
        user.last_name = request.form["last_name"]
        user.address_line1 = request.form["address_line1"]
        user.address_line2 = request.form["address_line2"]
        user.city = request.form["city"]
        user.postal_code = request.form["postal_code"]
        user.phone = request.form["phone"]

        db.session.commit()

        return redirect(url_for("profile.settings"))

    return render_template(
        "profile/settings.html",
        address_form=address_form,
        password_form=password_form
    )

@bp.route("/change-password", methods=["GET", "POST"])
@error_handler
@login_required
def change_password():
    if g.user is None:
        raise RequestException("Unauthorized", 401)

    password_form = ChangePasswordForm(request.form)

    if not password_form.validate():
        raise RequestException("New password fields must match", 400)

    if not check_password_hash(g.user.password, password_form.current_password.data):
        raise RequestException("Incorrect password", 400)
    
    user = db.get_or_404(User, g.user.id)
    user.password = generate_password_hash(password_form.new_password.data)
    db.session.commit()

    return redirect(url_for("profile.settings"))

server/print3dstore/templates/profile/orders.html
{% extends 'profile/wrapper.html' %}

{% block information %}
<h2>Orders</h2>
<ul class="list-group">
  {% for order in g.user.orders %}
    <li class="list-group-item">
      Order #{{ order.id }}
      <ul class="list-group">
        {% for stl_model in order.stl_models %}
          <li class="list-group-item">
            {% if stl_model.estimated_time and stl_model.estimated_cost %}
              {% set estimated_time = stl_model.estimated_time / 3600 %}
              BGN {{ stl_model.estimated_cost / 100.0 }} lv. --
              {{ estimated_time |round(method='ceil')|int }}h
            {% else %}
              {% if stl_model.errors is not none %}
                {{ stl_model.errors }}
              {% else %}
                No estimates. <a href="{{ url_for('order.retry_slice', order_id=order.id) }}">Click here to refresh</a>
              {% endif %}
            {% endif %}
            <a href="{{ url_for('media.static', filename=order.stl_models[0].file.full_path.split('/')[-1]) }}" class="view-model float-end" data-bs-toggle="modal" data-bs-target="#exampleModal">View model</a>
          </li>
        {% endfor %}
      </ul>
      {% endfor %}
    </li>
</ul>
<div class="modal fade" id="exampleModal">
  <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container d-flex flex-column align-items-center">
          <div id="stl-viewer" style="height: 600px; width: 1100px"></div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

server/print3dstore/templates/profile/profile.html
{% extends 'profile/wrapper.html' %}

{% block information %}
  <h2>Welcome to your dashboard, {{ g.user.first_name | default("User", true) }}!</h2>
    <div class="row">
      <div class="col-lg p-1">
        <h3>Your orders</h3>
        <div class="list-group">
          {% for order in g.user.orders %}
            {% set pill_class = 'bg-primary' %}
            {% if order.status == "in progress" %}
              {% set pill_class = 'bg-info' %}
            {% elif order.status == 'shipped' %}
              {% set pill_class = 'bg-info' %}
            {% elif order.status == 'finished' %}
              {% set pill_class = 'bg-success' %}
            {% elif order.status == 'canceled' %}
              {% set pill_class = 'bg-danger' %}
            {% endif %}
            <div class="list-group-item d-flex justify-content-between">
              Order #{{ order.id }}
              <span class="badge {{ pill_class }} rounded-pill">{{ order.status }}</span>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg p-1 d-flex flex-column justify-content-end text-center">
        <a class="btn btn-primary m-2" href="{{ url_for('order.order') }}">
          Order new
        </a>
      </div>
    </div>
{% endblock %}

server/print3dstore/templates/profile/settings.html
{% extends 'profile/wrapper.html' %}

{% block information %}
<h2>Profile Settings</h2>
<div class="mb-5">
  <h3>Profile Information</h3>
  <form action="{{ url_for('profile.settings')}}" method="post" enctype="multipart/form-data">
    {% for field in address_form %}
      {% if field.id != "csrf_token" %}
        {% if field.errors %}
          {{ field.label(class="form-label mt-4 is-invalid") }}<br>
        {% else %}
          {{ field.label(class="form-label mt-4") }}<br>
        {% endif %}
      {% endif %}
        {{ field }}
      {% if field.errors %}
      <div class="invalid-feedback">
        <ul class="errors">
          {% for error in field.errors %}
          <li>
            {{ error }}
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    {% endfor %}
    <button class="btn mt-4">Save</button>
  </form>
</div>
<div class="mb-5">

  <h3>Change password</h3>
  <form action="{{ url_for('profile.change_password')}}" method="post" enctype="multipart/form-data">
    {% for field in password_form %}
      {% if field.id != "csrf_token" %}
      {% if field.errors %}
      {{ field.label(class="form-label mt-4 is-invalid") }}<br>
      {% else %}
      {{ field.label(class="form-label mt-4") }}<br>
      {% endif %}
      {% endif %}
      {{ field }}
      {% if field.errors %}
      <div class="invalid-feedback">
        <ul class="errors">
          {% for error in field.errors %}
          <li>
            {{ error }}
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    {% endfor %}
    <button class="btn mt-4">Submit</button>
  </form>
</div>
{% endblock %}

server/print3dstore/templates/profile/wrapper.html
{% extends 'base.html' %}

{% block content %}
  <h1>Dashboard</h1>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 mb-4">
        <ul class="list-group">
          <a href="{{ url_for('profile.info') }}">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Profile
            </li>
          </a>
          <a href="{{ url_for('profile.orders') }}">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Orders
            </li>
          </a>
          <a href="{{ url_for('profile.settings') }}">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Settings
            </li>
          </a>
          <a href="{{ url_for('auth.logout') }}">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Log out
            </li>
          </a>
        </ul>
      </div>
      <div class="col">
        <div class="card p-4">
          {% block information %}
            
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}